<?php return array(
    'root' => array(
        'name' => 'yiisoft/yii2-app-advanced',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '47e2e1f535c380f70e88de85a8cc1df8f4aaf30d',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'adldap2/adldap2' => array(
            'pretty_version' => 'v10.5.0',
            'version' => '10.5.0.0',
            'reference' => 'e400eecb7bd7de8ee79aae320b54ad70d37f86b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../adldap2/adldap2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'behat/gherkin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '01379b1f9bc67a9040a472d069f1ee34cbe1b1b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/gherkin',
            'aliases' => array(
                0 => '4.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'bower-asset/bootstrap' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'reference' => '60098ac499d30aa50575b0b7137391c06ef25429',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/inputmask' => array(
            'pretty_version' => '3.3.11',
            'version' => '3.3.11.0',
            'reference' => '5e670ad62f50c738388d4dcec78d2888505ad77b',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/inputmask',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/jquery' => array(
            'pretty_version' => '3.6.4',
            'version' => '3.6.4.0',
            'reference' => '91ef2d8836342875f2519b5815197ea0f23613cf',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/punycode' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'reference' => '38c8d3131a82567bfef18da09f7f4db68c84f8a3',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/punycode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/yii2-pjax' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'reference' => 'a9298d57da63d14a950f1b94366a864bc62264fb',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/yii2-pjax',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cebe/markdown' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '2b2461bed9e15305486319ee552bafca75d1cdaa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cebe/markdown',
            'aliases' => array(
                0 => '1.2.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'codeception/codeception' => array(
            'pretty_version' => '4.2.x-dev',
            'version' => '4.2.9999999.9999999-dev',
            'reference' => 'c21e4fee784f6ae8eb2a9617b90f47cd28f82d80',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/codeception',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/lib-asserts' => array(
            'pretty_version' => '1.13.2',
            'version' => '1.13.2.0',
            'reference' => '184231d5eab66bc69afd6b9429344d80c67a33b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-asserts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/lib-innerbrowser' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '31b4b56ad53c3464fcb2c0a14d55a51a201bd3c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-innerbrowser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/module-asserts' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '59374f2fef0cabb9e8ddb53277e85cdca74328de',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-asserts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/module-filesystem' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => 'cc34791c9d56d6481fb033e7999d728b71415a11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-filesystem',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/module-yii2' => array(
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'reference' => '14269d059b8eaedf3d414a673907bd874cd4ed04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-yii2',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/phpunit-wrapper' => array(
            'pretty_version' => '9.0.x-dev',
            'version' => '9.0.9999999.9999999-dev',
            'reference' => '7439a53ae367986e9c22b2ac00f9d7376bb2f8cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/phpunit-wrapper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/stub' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'reference' => '18a148dacd293fc7b044042f5aa63a82b08bff5d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/stub',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/verify' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '2f8f5ce6ea1be5c011f77eb7f1ca0c9f4d551513',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/verify',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => 'eac01fbdf4e4a3635169b056608730ec0930e188',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.x-dev',
            'version' => '1.5.9999999.9999999-dev',
            'reference' => '0a0fa9780f5d4e507415a065172d26a98d02047b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '2.1.x-dev',
            'version' => '2.1.9999999.9999999-dev',
            'reference' => 'e74756f7517d72c238b9163fcd1ed54eb1f92bd0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'edvlerblog/yii2-adldap-module' => array(
            'pretty_version' => 'v6.0.0',
            'version' => '6.0.0.0',
            'reference' => '6f8fef9efebdf20c3b6b42a56a6d4284e2e01778',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../edvlerblog/yii2-adldap-module',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '3.x-dev',
            'version' => '3.9999999.9999999.9999999-dev',
            'reference' => 'e5997fa97e8790cdae03a9cbd5e78e45e3c7bda7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.16.0',
            'version' => '4.16.0.0',
            'reference' => '523407fb06eb9e5f3d59889b3978d5bfe94299c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.22.0',
            'version' => '1.22.0.0',
            'reference' => 'f85772abd508bd04e20bb4b1bbe260a68d0066d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.6.x-dev',
            'version' => '2.6.9999999.9999999-dev',
            'reference' => 'b635f279edd83fc275f822a1188157ffea568ff6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'illuminate/contracts' => array(
            'pretty_version' => '8.x-dev',
            'version' => '8.9999999.9999999.9999999-dev',
            'reference' => '5e0fd287a1b22a6b346a9f7cd484d8cf0234585d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-fileinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '8f4a40fdb3c4aa6dc1d80ab72f05d6f0dd9ab0a4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-fileinput',
            'aliases' => array(
                0 => '5.5.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-star-rating' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '6f8575fe14ca186ff80aa776c4e234fd5b26af83',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-star-rating',
            'aliases' => array(
                0 => '4.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/dependent-dropdown' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'c9e0b2b5b58ad717842396053804f8d0281df1ae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/dependent-dropdown',
            'aliases' => array(
                0 => '1.4.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-krajee-base' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5c095126d1be47e0bb1f92779b7dc099f6feae31',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-krajee-base',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-activeform' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '98dbf789c9f71a35c76a8c2b667e86815ae51ac1',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-activeform',
            'aliases' => array(
                0 => '1.6.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-affix' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '7f3266b1989ffd54a7025c4b1a322fcec38a9665',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-affix',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-alert' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '6a45d7dc294eecd578cf8cb9acb671d1cafa0727',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-alert',
            'aliases' => array(
                0 => '1.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-colorinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'df15b4803eaadc094a5274b41381d2b585961be2',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-colorinput',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datepicker' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '04ee13be77790ee14d92c34f3181e521f6457639',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datepicker',
            'aliases' => array(
                0 => '1.4.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datetimepicker' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '85b22d38553ca207f86be198f37e6531347e9a23',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datetimepicker',
            'aliases' => array(
                0 => '1.5.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-depdrop' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '4dffe1fd0c9d9d5b7e6231f6cd059dfa36d22b3b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-depdrop',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-fileinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'b5500b6855526837154694c2afab8dbc3afc8abd',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-fileinput',
            'aliases' => array(
                0 => '1.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-growl' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '80b4a4da28b59e95b909b24b4aa5d6eb1765d2c9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-growl',
            'aliases' => array(
                0 => '1.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-rangeinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'c27f7c90299df5707fdd35ef2617042ce32b891c',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-rangeinput',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-rating' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'd3d7249490044f80e65f8f3938191f39a76586b2',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-rating',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-select2' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '4b8ef7dd9780531fc997fa23a53a38a1f7674bec',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-select2',
            'aliases' => array(
                0 => '2.2.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-sidenav' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5d3276503d224f73c34f1010d6bc6dd4e936c50f',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-sidenav',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-spinner' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'db22bd63fd1c1d3f9d8aa9477842f16338050ff1',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-spinner',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-switchinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '10afe2ac8274da9371b43aaf69e99fc553f1b947',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-switchinput',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-timepicker' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '680aec2d79846e926c072da455cf6f33e1c3bb12',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-timepicker',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-touchspin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '1eec4c3f3a8bf9a170e1e0682c2c89f2929d65e9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-touchspin',
            'aliases' => array(
                0 => '1.2.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-typeahead' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5335af5263a692d0559dd9f92fd6a2a5a4393760',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-typeahead',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widgets' => array(
            'pretty_version' => 'v3.4.1',
            'version' => '3.4.1.0',
            'reference' => 'e5a030d700243a90eccf96a070380bd3b76e17a3',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widgets',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '928a96f585b86224ebc78f8f09d0482cf15b04f5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => '4.x-dev',
            'version' => '4.9999999.9999999.9999999-dev',
            'reference' => 'c9e5a13d68486e9fd75f9be1b4639644e54e7f4f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '64f3265002e9e181436942aac2fbd482e186dc55',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '67729272c564ab9f953c81f48db44e8b1cb1e1c3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpspec/php-diff' => array(
            'pretty_version' => 'v1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'fc1156187f9f6c8395886fe85ed88a0a245d72e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/php-diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.x-dev',
            'version' => '9.2.9999999.9999999-dev',
            'reference' => '100663232669bdacd3ac18f4cc12c38beec9aff1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.x-dev',
            'version' => '3.0.9999999.9999999-dev',
            'reference' => '38b24367e1b340aa78b96d7cab042942d917bb84',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.28',
            'version' => '9.5.28.0',
            'reference' => '954ca3113a03bf780d22f07bf055d883ee04b65e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'e275e2d67d53964a3f13e056886ecd769edee021',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '6d70f402f0eddb2b154b22950b5381bbf5b28469',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.x-dev',
            'version' => '4.0.9999999.9999999-dev',
            'reference' => 'b247957a1c8dc81a671770f74b479c0a78a818f1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.x-dev',
            'version' => '4.0.9999999.9999999-dev',
            'reference' => '74be17022044ebaaecfdf0c5cd504fc9cd5a7131',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.x-dev',
            'version' => '5.1.9999999.9999999-dev',
            'reference' => '830c43a844f1f8d5b7a1f6d6076b784454d8b7ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.x-dev',
            'version' => '4.0.9999999.9999999-dev',
            'reference' => 'ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.x-dev',
            'version' => '5.0.9999999.9999999-dev',
            'reference' => '0ca8db5a5fc9c8646244e629625ac486fa286bf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.x-dev',
            'version' => '4.0.9999999.9999999-dev',
            'reference' => 'e75bd0f07204fec2a0af9b0f3cfe97d05f92efc1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '20bdda85c7c585ab265c0c37ec052a019bae29c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.2.x-dev',
            'version' => '3.2.9999999.9999999-dev',
            'reference' => '75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.x-dev',
            'version' => '3.0.9999999.9999999-dev',
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'select2/select2' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'reference' => '4de1d236e602149a5c78d35899b49b3989b94107',
            'type' => 'component',
            'install_path' => __DIR__ . '/../select2/select2',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v4.2.4',
            'version' => '4.2.4.0',
            'reference' => '61d85c5af2fc058014c7c89504c3944e73a086f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/console' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '560fc3ed7a43e6d30ea94a07d77f9a60b8ed0fb8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '95f3c7468db1da8cc360b24fa2a26e7cefcb355d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'reference' => '80d075412b557d41002320b96a096ca65aa2c98d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => '4.4.x-dev',
            'version' => '4.4.9999999.9999999-dev',
            'reference' => '4b8daf6c56801e6d664224261cb100b73edc78a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '1df20e45d56da29a4b1d8259dd6e950acbf1b13f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'reference' => 'e3365cc6454a9b68d010ccf5c99dab0fb71e2f77',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/finder' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '078e9a5e1871fcfe6a5ce421b539344c21afef19',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/mailer' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '6330cd465dfd8b7a07515757a1c37069075f7b0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => 'ae0a1032a450a3abf305ee44fc55ed423fbf16e3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'ea208ce43cbb04af6867b4fdddb1bdbf84cc28cb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '875e90aeea2777b6f135677f618529449334a612',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'ecaafce9f77234a6a449d29e49267ba10499116d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'f9c7affe77a00ae32ca127ca6833d034e6d33f25',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '70f4aebd92afca2f865444d30a4d2151c13c3179',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'fe2f306d1d9d346a7fee353d0d5012e401e984b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '6caa57379c4aec19c0a12a38b59b26487dcfe4b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'reference' => 'a2329596ddc8fd568900e3fc76cba42489ecc7f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '8036a4c76c0dd29e60b6a7cafcacc50cf088ea62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '4684507543cf80a3819bb36dc868a6ff35a5eec7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '4cd2e3ea301aadd76a4172756296fe552fb45b0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tightenco/collect' => array(
            'pretty_version' => 'v8.83.27',
            'version' => '8.83.27.0',
            'reference' => '07eed6cf7441c7a69c379fdcb118eec1a1fdd0e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tightenco/collect',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twbs/bootstrap-icons' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'fb2fcb123d526ecbc89a79fcec961d23fe355aef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twbs/bootstrap-icons',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '64f8d3794f1a3459e08499994ca0b4dee4ef45b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yiisoft/yii2',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-app-advanced' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '47e2e1f535c380f70e88de85a8cc1df8f4aaf30d',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-bootstrap5' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5ea4bb6dc7f729835b5ace59721932f66e1b05de',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-bootstrap5',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-composer' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '54ae854b66445daa6195c3c86e6d517d47e071ea',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../yiisoft/yii2-composer',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-debug' => array(
            'pretty_version' => '2.1.23',
            'version' => '2.1.23.0',
            'reference' => '73af53bd1b99d40f983ba57386ac6c374d9ef177',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-debug',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-faker' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '98e4e4ca1aa38282af598dd2e7f658c7090d22e5',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-faker',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-gii' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'reference' => 'ac574e7e2c29fd865145c8688719f252d19aae23',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-gii',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-symfonymailer' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '82f5902551a160633c4734b5096977ce76a809d9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-symfonymailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
